<?php
/* @var $this Mage_Reports_Block_Product_Viewed */
?>
<script id="recently-viewed-product-list" type="template/text">
    <div class="block block-list block-viewed">
        <div class="block-title">
            <strong><span><?php echo $this->__('Recently Viewed Products') ?></span></strong>
        </div>
        <div class="block-content">
            <ol id="recently-viewed-items" class="mini-products-list">
            </ol>
        </div>
    </div>
</script>