<?php $_product = Mage::registry('current_product'); ?>
<script id="recently-viewed" type="template/html">
    <li class="item">
        <a href="<?php echo $this->getProductUrl($_product) ?>">
            <span class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(50, 50)->setWatermarkSize('30x10'); ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /></span>
        </a>
        <div class="product-details">
            <p class="product-name">
                <a href="<?php echo $this->getProductUrl($_product) ?>">
                    <?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?>
                </a>
            </p>
        </div>
    </li>
</script>